
package vista;

import javax.swing.ImageIcon;

public class vistaEMPLEADO extends javax.swing.JFrame {

    
    public vistaEMPLEADO() {
        initComponents();
        setLocationRelativeTo(this);
        //cambiar el icono por defecto de NETBEANS        
        setIconImage(new ImageIcon("C:\\Users\\MAFOWS21\\Documents\\PC's RESUELTA seccion X\\RETO DE LAS SEMANA 7 (Presentacion)\\S_G_E_V\\src\\main\\java\\imagenes\\empleado.png").getImage());
        
        jlDNI.setVisible(false);
        txtDNI.setVisible(false);
        
        
        
        jlCARNET.setVisible(false);
        jlPASAPORTE.setVisible(false);
                
        txtEXTRANJERIA.setVisible(false);
        txtPASAPORTE.setVisible(false);
                
        jlRESIDENTE.setVisible(false);
        rbtnSI.setVisible(false);
        rbtnNO.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGRP_ASOCIACION = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jl_EMPLEADO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDISTRITO = new javax.swing.JTextField();
        cbxSEXO = new javax.swing.JComboBox<>();
        txtID_EMPLEADO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxNACIONALIDAD = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtN_A = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCORREO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDIRECCION = new javax.swing.JTextField();
        btnREGRESAR = new javax.swing.JButton();
        btnREGISTRAR = new javax.swing.JButton();
        jlDNI = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFECHA = new javax.swing.JTextField();
        rbtnSI = new javax.swing.JRadioButton();
        rbtnNO = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtTELEFONO = new javax.swing.JTextField();
        jlPASAPORTE = new javax.swing.JLabel();
        jlCARNET = new javax.swing.JLabel();
        txtEXTRANJERIA = new javax.swing.JTextField();
        txtPASAPORTE = new javax.swing.JTextField();
        jlRESIDENTE = new javax.swing.JLabel();
        btnLIMPIAR = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO DE EMPLEADOS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_EMPLEADO.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jl_EMPLEADO.setForeground(new java.awt.Color(255, 0, 0));
        jl_EMPLEADO.setText("Registro de Empleado");
        getContentPane().add(jl_EMPLEADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 360, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("<html>Fecha de Nacimiento:</html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 40));

        txtDISTRITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDISTRITOActionPerformed(evt);
            }
        });
        getContentPane().add(txtDISTRITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 150, -1));

        cbxSEXO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbxSEXO.setSelectedIndex(-1);
        getContentPane().add(cbxSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, 20));

        txtID_EMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_EMPLEADOActionPerformed(evt);
            }
        });
        getContentPane().add(txtID_EMPLEADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 60, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("<html>Nombres y Apellidos:</html>");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 40));

        cbxNACIONALIDAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No especificado", "Peruana", "Extranjera" }));
        cbxNACIONALIDAD.setSelectedIndex(-1);
        cbxNACIONALIDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNACIONALIDADActionPerformed(evt);
            }
        });
        getContentPane().add(cbxNACIONALIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 20));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Distrito:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, 40));

        txtN_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN_AActionPerformed(evt);
            }
        });
        getContentPane().add(txtN_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 190, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 40, 40));

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 110, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Telefono:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, 40));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Correo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, 40));

        txtCORREO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCORREOActionPerformed(evt);
            }
        });
        getContentPane().add(txtCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 150, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Direccion:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 70, 40));

        txtDIRECCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDIRECCIONActionPerformed(evt);
            }
        });
        getContentPane().add(txtDIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 150, -1));

        btnREGRESAR.setBackground(new java.awt.Color(0, 153, 0));
        btnREGRESAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnREGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        btnREGRESAR.setText("regresar");
        getContentPane().add(btnREGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 146, 52));

        btnREGISTRAR.setBackground(new java.awt.Color(255, 0, 255));
        btnREGISTRAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnREGISTRAR.setForeground(new java.awt.Color(255, 255, 255));
        btnREGISTRAR.setText("REGISTRAR");
        getContentPane().add(btnREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 146, 52));

        jlDNI.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlDNI.setText("DNI:");
        getContentPane().add(jlDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 40, 40));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setText("idEmpleado:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtFECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFECHAActionPerformed(evt);
            }
        });
        getContentPane().add(txtFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, -1));

        btnGRP_ASOCIACION.add(rbtnSI);
        rbtnSI.setText("Si");
        getContentPane().add(rbtnSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 40, -1));

        btnGRP_ASOCIACION.add(rbtnNO);
        rbtnNO.setText("No");
        getContentPane().add(rbtnNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Nacionalidad:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtTELEFONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTELEFONOActionPerformed(evt);
            }
        });
        getContentPane().add(txtTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 110, -1));

        jlPASAPORTE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlPASAPORTE.setText("Pasaporte");
        getContentPane().add(jlPASAPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 70, 50));

        jlCARNET.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlCARNET.setText("<html>Carnet de Extranjeria:</html>");
        getContentPane().add(jlCARNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 100, 50));

        txtEXTRANJERIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEXTRANJERIAActionPerformed(evt);
            }
        });
        getContentPane().add(txtEXTRANJERIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 110, -1));

        txtPASAPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPASAPORTEActionPerformed(evt);
            }
        });
        getContentPane().add(txtPASAPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 110, -1));

        jlRESIDENTE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlRESIDENTE.setText("<html>Eres residente en Peru</html>");
        getContentPane().add(jlRESIDENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, 60));

        btnLIMPIAR.setBackground(new java.awt.Color(102, 102, 102));
        btnLIMPIAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnLIMPIAR.setForeground(new java.awt.Color(255, 255, 255));
        btnLIMPIAR.setText("LIMPIAR");
        getContentPane().add(btnLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 146, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDISTRITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDISTRITOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDISTRITOActionPerformed

    private void txtFECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFECHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFECHAActionPerformed

    private void txtDIRECCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDIRECCIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDIRECCIONActionPerformed

    private void txtCORREOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCORREOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCORREOActionPerformed

    private void txtPASAPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPASAPORTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPASAPORTEActionPerformed

    private void txtEXTRANJERIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEXTRANJERIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEXTRANJERIAActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtN_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN_AActionPerformed

    private void txtTELEFONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTELEFONOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTELEFONOActionPerformed

    private void txtID_EMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_EMPLEADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_EMPLEADOActionPerformed

    private void cbxNACIONALIDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNACIONALIDADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNACIONALIDADActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btnGRP_ASOCIACION;
    public javax.swing.JButton btnLIMPIAR;
    public javax.swing.JButton btnREGISTRAR;
    public javax.swing.JButton btnREGRESAR;
    public javax.swing.JComboBox<String> cbxNACIONALIDAD;
    public javax.swing.JComboBox<String> cbxSEXO;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel jlCARNET;
    public javax.swing.JLabel jlDNI;
    public javax.swing.JLabel jlPASAPORTE;
    public javax.swing.JLabel jlRESIDENTE;
    public javax.swing.JLabel jl_EMPLEADO;
    public javax.swing.JRadioButton rbtnNO;
    public javax.swing.JRadioButton rbtnSI;
    public javax.swing.JTextField txtCORREO;
    public javax.swing.JTextField txtDIRECCION;
    public javax.swing.JTextField txtDISTRITO;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtEXTRANJERIA;
    public javax.swing.JTextField txtFECHA;
    public javax.swing.JTextField txtID_EMPLEADO;
    public javax.swing.JTextField txtN_A;
    public javax.swing.JTextField txtPASAPORTE;
    public javax.swing.JTextField txtTELEFONO;
    // End of variables declaration//GEN-END:variables
}
