
package vista;

import javax.swing.ImageIcon;


public class vistaCLIENTE extends javax.swing.JFrame {

    
    public vistaCLIENTE() {
        initComponents();
        setLocationRelativeTo(this);   
        //cambiar el icono por defecto de NETBEANS        
        setIconImage(new ImageIcon("C:\\Users\\MAFOWS21\\Documents\\PC's RESUELTA seccion X\\RETO DE LAS SEMANA 7 (Presentacion)\\S_G_E_V\\src\\main\\java\\imagenes\\cliente.png").getImage());
        
        jlDNI.setVisible(false);
        txtDNI.setVisible(false);
        
        
        
        jlCARNET.setVisible(false);
        jlPASAPORTE.setVisible(false);
                
        txtEXTRANJERIA.setVisible(false);
        txtPASAPORTE.setVisible(false);
                
        jlRESIDENTE.setVisible(false);
        rbtnSI.setVisible(false);
        rbtnNO.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGRP_ASOCIACION = new javax.swing.ButtonGroup();
        cbxNACIONALIDAD = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtN_A = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLICENCIA = new javax.swing.JTextField();
        txtDISTRITO = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTELEFONO = new javax.swing.JTextField();
        cbxSEXO = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCORREO = new javax.swing.JTextField();
        txtID_CLIENTE = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDIRECCION = new javax.swing.JTextField();
        jl_CLIENTE = new javax.swing.JLabel();
        jlRESIDENTE = new javax.swing.JLabel();
        rbtnSI = new javax.swing.JRadioButton();
        rbtnNO = new javax.swing.JRadioButton();
        jlPASAPORTE = new javax.swing.JLabel();
        jlCARNET = new javax.swing.JLabel();
        txtEXTRANJERIA = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtPASAPORTE = new javax.swing.JTextField();
        jlDNI = new javax.swing.JLabel();
        btnREGRESAR = new javax.swing.JButton();
        btnREGISTRAR = new javax.swing.JButton();
        btnLIMPIAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Clientes");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxNACIONALIDAD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No especificado", "Peruana", "Extranjera" }));
        cbxNACIONALIDAD.setSelectedIndex(-1);
        cbxNACIONALIDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNACIONALIDADActionPerformed(evt);
            }
        });
        getContentPane().add(cbxNACIONALIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, 20));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setText("Distrito:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 60, 40));

        txtN_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN_AActionPerformed(evt);
            }
        });
        getContentPane().add(txtN_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 190, -1));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setText("Sexo:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 40, 40));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setText("<html>Nro. de Licencia (Brevete):</html>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 50));

        txtLICENCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLICENCIAActionPerformed(evt);
            }
        });
        getContentPane().add(txtLICENCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 110, -1));

        txtDISTRITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDISTRITOActionPerformed(evt);
            }
        });
        getContentPane().add(txtDISTRITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 150, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setText("Telefono:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, 40));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setText("idCliente:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txtTELEFONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTELEFONOActionPerformed(evt);
            }
        });
        getContentPane().add(txtTELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, -1));

        cbxSEXO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbxSEXO.setSelectedIndex(-1);
        getContentPane().add(cbxSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, 20));

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setText("Correo:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 50, 40));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setText("Nacionalidad:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txtCORREO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCORREOActionPerformed(evt);
            }
        });
        getContentPane().add(txtCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, -1));

        txtID_CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_CLIENTEActionPerformed(evt);
            }
        });
        getContentPane().add(txtID_CLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 60, -1));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setText("Direccion:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 80, 40));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setText("<html>Nombres y Apellidos:</html>");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 40));

        txtDIRECCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDIRECCIONActionPerformed(evt);
            }
        });
        getContentPane().add(txtDIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 150, -1));

        jl_CLIENTE.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jl_CLIENTE.setForeground(new java.awt.Color(0, 51, 255));
        jl_CLIENTE.setText("Registro de Cliente");
        getContentPane().add(jl_CLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, -1));

        jlRESIDENTE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlRESIDENTE.setText("<html>Eres residente en Peru</html>");
        getContentPane().add(jlRESIDENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, 60));

        btnGRP_ASOCIACION.add(rbtnSI);
        rbtnSI.setText("Si");
        getContentPane().add(rbtnSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 40, -1));

        btnGRP_ASOCIACION.add(rbtnNO);
        rbtnNO.setText("No");
        getContentPane().add(rbtnNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        jlPASAPORTE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlPASAPORTE.setText("Pasaporte");
        getContentPane().add(jlPASAPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 70, 50));

        jlCARNET.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlCARNET.setText("<html>Carnet de Extranjeria:</html>");
        getContentPane().add(jlCARNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 80, 50));

        txtEXTRANJERIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEXTRANJERIAActionPerformed(evt);
            }
        });
        getContentPane().add(txtEXTRANJERIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 110, -1));

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 110, -1));

        txtPASAPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPASAPORTEActionPerformed(evt);
            }
        });
        getContentPane().add(txtPASAPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 110, -1));

        jlDNI.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlDNI.setText("DNI:");
        getContentPane().add(jlDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 40, 40));

        btnREGRESAR.setBackground(new java.awt.Color(0, 153, 0));
        btnREGRESAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnREGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        btnREGRESAR.setText("regresar");
        getContentPane().add(btnREGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 146, 52));

        btnREGISTRAR.setBackground(new java.awt.Color(0, 255, 204));
        btnREGISTRAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnREGISTRAR.setForeground(new java.awt.Color(255, 255, 255));
        btnREGISTRAR.setText("REGISTRAR");
        getContentPane().add(btnREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 146, 52));

        btnLIMPIAR.setBackground(new java.awt.Color(102, 102, 102));
        btnLIMPIAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnLIMPIAR.setForeground(new java.awt.Color(255, 255, 255));
        btnLIMPIAR.setText("LIMPIAR");
        getContentPane().add(btnLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 146, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtN_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN_AActionPerformed

    private void txtLICENCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLICENCIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLICENCIAActionPerformed

    private void txtDISTRITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDISTRITOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDISTRITOActionPerformed

    private void txtTELEFONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTELEFONOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTELEFONOActionPerformed

    private void txtCORREOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCORREOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCORREOActionPerformed

    private void txtID_CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_CLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_CLIENTEActionPerformed

    private void txtDIRECCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDIRECCIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDIRECCIONActionPerformed

    private void txtEXTRANJERIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEXTRANJERIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEXTRANJERIAActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtPASAPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPASAPORTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPASAPORTEActionPerformed

    private void cbxNACIONALIDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNACIONALIDADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNACIONALIDADActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btnGRP_ASOCIACION;
    public javax.swing.JButton btnLIMPIAR;
    public javax.swing.JButton btnREGISTRAR;
    public javax.swing.JButton btnREGRESAR;
    public javax.swing.JComboBox<String> cbxNACIONALIDAD;
    public javax.swing.JComboBox<String> cbxSEXO;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jlCARNET;
    public javax.swing.JLabel jlDNI;
    public javax.swing.JLabel jlPASAPORTE;
    public javax.swing.JLabel jlRESIDENTE;
    public javax.swing.JLabel jl_CLIENTE;
    public javax.swing.JRadioButton rbtnNO;
    public javax.swing.JRadioButton rbtnSI;
    public javax.swing.JTextField txtCORREO;
    public javax.swing.JTextField txtDIRECCION;
    public javax.swing.JTextField txtDISTRITO;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtEXTRANJERIA;
    public javax.swing.JTextField txtID_CLIENTE;
    public javax.swing.JTextField txtLICENCIA;
    public javax.swing.JTextField txtN_A;
    public javax.swing.JTextField txtPASAPORTE;
    public javax.swing.JTextField txtTELEFONO;
    // End of variables declaration//GEN-END:variables
}
