
package vista;


import javax.swing.ImageIcon;



public class vistaVEHICULO extends javax.swing.JFrame {

    
    public vistaVEHICULO() {
        initComponents();
        setLocationRelativeTo(this);   
        //cambiar el icono por defecto de NETBEANS        
        setIconImage(new ImageIcon("C:\\Users\\MAFOWS21\\Documents\\PC's RESUELTA seccion X\\RETO DE LAS SEMANA 7 (Presentacion)\\S_G_E_V\\src\\main\\java\\imagenes\\vehiculo.png").getImage());
        
//        jlDNI.setVisible(false);
//        txtDNI.setVisible(false);
//        
//        
//        
//        jlCARNET.setVisible(false);
//        jlPASAPORTE.setVisible(false);
//                
//        txtEXTRANJERIA.setVisible(false);
//        txtPASAPORTE.setVisible(false);
//                
//        jlRESIDENTE.setVisible(false);
//        rbtnSI.setVisible(false);
//        rbtnNO.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGRP_ASOCIACION = new javax.swing.ButtonGroup();
        cbxTIPO = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxMODELO = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jl_VEHICULO = new javax.swing.JLabel();
        jlRESIDENTE = new javax.swing.JLabel();
        rbtnSI = new javax.swing.JRadioButton();
        rbtnNO = new javax.swing.JRadioButton();
        btnREGRESAR = new javax.swing.JButton();
        btnREGISTRAR = new javax.swing.JButton();
        cbxMARCA = new javax.swing.JComboBox<>();
        cbxCOLOR = new javax.swing.JComboBox<>();
        jlRESIDENTE1 = new javax.swing.JLabel();
        txtPLACA = new javax.swing.JTextField();
        btnLIMPIAR = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtID_VEHICULO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Vehiculos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No especificado", "Sedan", "SUV", "Pickup" }));
        cbxTIPO.setSelectedIndex(-1);
        getContentPane().add(cbxTIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, 20));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setText("Modelo:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 40));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setText("Color:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 50, 50));

        getContentPane().add(cbxMODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 120, 20));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setText("ID:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setText("Marca:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 50, 40));

        jl_VEHICULO.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jl_VEHICULO.setForeground(new java.awt.Color(0, 0, 0));
        jl_VEHICULO.setText("Registro de Vehiculo");
        getContentPane().add(jl_VEHICULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 330, -1));

        jlRESIDENTE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlRESIDENTE.setText("Nro. Placa:");
        getContentPane().add(jlRESIDENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 80, 60));

        btnGRP_ASOCIACION.add(rbtnSI);
        rbtnSI.setText("Si");
        getContentPane().add(rbtnSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 40, -1));

        btnGRP_ASOCIACION.add(rbtnNO);
        rbtnNO.setText("No");
        getContentPane().add(rbtnNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        btnREGRESAR.setBackground(new java.awt.Color(0, 153, 0));
        btnREGRESAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnREGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        btnREGRESAR.setText("regresar");
        getContentPane().add(btnREGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 146, 52));

        btnREGISTRAR.setBackground(new java.awt.Color(255, 153, 51));
        btnREGISTRAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnREGISTRAR.setForeground(new java.awt.Color(255, 255, 255));
        btnREGISTRAR.setText("REGISTRAR");
        getContentPane().add(btnREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 146, 52));

        cbxMARCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOYOTA", "NISSAN", "HONDA", "FORD" }));
        cbxMARCA.setSelectedIndex(-1);
        cbxMARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMARCAActionPerformed(evt);
            }
        });
        getContentPane().add(cbxMARCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 120, 20));

        cbxCOLOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No especificado", "Negro", "Gris", "Plata", "Azul", "Verde", "Rojo", "Amarillo", "Blanco" }));
        cbxCOLOR.setSelectedIndex(-1);
        getContentPane().add(cbxCOLOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 120, 20));

        jlRESIDENTE1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlRESIDENTE1.setText("<html>¿Lunas polarizadas?</html>");
        getContentPane().add(jlRESIDENTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 60));

        txtPLACA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPLACA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPLACAActionPerformed(evt);
            }
        });
        getContentPane().add(txtPLACA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 130, -1));

        btnLIMPIAR.setBackground(new java.awt.Color(102, 102, 102));
        btnLIMPIAR.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnLIMPIAR.setForeground(new java.awt.Color(255, 255, 255));
        btnLIMPIAR.setText("LIMPIAR");
        getContentPane().add(btnLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 146, 52));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setText("Tipo:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtID_VEHICULO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID_VEHICULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_VEHICULOActionPerformed(evt);
            }
        });
        getContentPane().add(txtID_VEHICULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMARCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMARCAActionPerformed

    private void txtPLACAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPLACAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPLACAActionPerformed

    private void txtID_VEHICULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_VEHICULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_VEHICULOActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btnGRP_ASOCIACION;
    public javax.swing.JButton btnLIMPIAR;
    public javax.swing.JButton btnREGISTRAR;
    public javax.swing.JButton btnREGRESAR;
    public javax.swing.JComboBox<String> cbxCOLOR;
    public javax.swing.JComboBox<String> cbxMARCA;
    public javax.swing.JComboBox<String> cbxMODELO;
    public javax.swing.JComboBox<String> cbxTIPO;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jlRESIDENTE;
    public javax.swing.JLabel jlRESIDENTE1;
    public javax.swing.JLabel jl_VEHICULO;
    public javax.swing.JRadioButton rbtnNO;
    public javax.swing.JRadioButton rbtnSI;
    public javax.swing.JTextField txtID_VEHICULO;
    public javax.swing.JTextField txtPLACA;
    // End of variables declaration//GEN-END:variables
}
